language: "en-US"

tone_instructions: "Please call me Boss!"

early_access: false

reviews:
  profile: "assertive"
  commit_status: true
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  review_details: true
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main

chat:
  auto_reply: true
